#application name
spring.application.name=studypair-app

#PostgrelSql database connection settings
spring.datasource.url=jdbc:postgresql://localhost:5432/studypair
spring.datasource.username=postgres
spring.datasource.password=20040830S
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

#server port
server.port=8080

#Java web token (JWT) secret key
app.jwt.secret= studyPairSecretKeyForJWT2924VeryLongSecure
app.jwt.expiration=86400000

